#!/bin/bash
#
# This file is part of the Offenbach Project
#
# (c) 2019-2025 Yannoff (https://github.com/yannoff)
#
# @project  Offenbach
# @author   Yannoff (https://github.com/yannoff)
# @link     https://github.com/yannoff/offenbach
# @license  http://opensource.org/licenses/MIT
#
# For the full copyright and license information,
# please view the LICENSE file bundled with this
# software sources.
#
# For internal use only
#

echo -n "-- checking wether CURL is installed... " >&2

if [ -n "`which curl`" ]
then
    echo "yes" >&2
else
    printf "no\n\n  %s\n\n" "Error: \"cURL\" not found, please install it to proceed." >&2
    exit 1
fi
