#!/bin/bash
#
# This file is part of the Offenbach Project
#
# (c) 2019-2022 Yannoff (https://github.com/yannoff)
#
# @project  Offenbach
# @author   Yannoff (https://github.com/yannoff)
# @link     https://github.com/yannoff/offenbach
# @license  http://opensource.org/licenses/MIT
#
# For the full copyright and license information,
# please view the LICENSE file bundled with this
# software sources.
#
# For internal use only
#

bindir=$1

echo -n "-- checking wether yamltools are installed... " >&2

if [ -n "`which yamltools`" ]
then
    echo "yes" >&2
else
    printf "no\n%s\n" "+ including download task in Makefile." >&2
    printf "\tcurl -Lo %s/yamltools https://github.com/yannoff/yamltools/releases/latest/download/yamltools\n" ${bindir} >&1
    printf "\tchmod +x %s/yamltools\n" ${bindir} >&1
fi
