#!/bin/bash
#
# This file is part of the Offenbach Project
#
# (c) 2019-2022 Yannoff (https://github.com/yannoff)
#
# @project  Offenbach
# @author   Yannoff (https://github.com/yannoff)
# @link     https://github.com/yannoff/offenbach
# @license  http://opensource.org/licenses/MIT
#
# For the full copyright and license information,
# please view the LICENSE file bundled with this
# software sources.
#
# For internal use only
#

bindir=$1
depfile=dependencies.yaml

echo -n "-- checking whether yamltools are installed... " >&2

required=$(awk -F ': ' '($1 == "yamltools") { print $2; }' ${depfile} | tr -d ' ')
installed=$(yamltools --version --raw 2>/dev/null)

if [ -z "${installed}" ] || [ ! "${installed//./}" -ge "${required//./}" ]
then
    printf "not installed or version requirement not met\n%s\n" "+ including download task in Makefile." >&2
    printf "\tcurl -Lo %s/yamltools https://github.com/yannoff/yamltools/releases/download/${required}/yamltools\n" ${bindir} >&1
    printf "\tchmod +x %s/yamltools\n" ${bindir} >&1
else
    echo "yes - version ${installed}" >&2
fi
